spring:
  datasource:
    url: ZGjewwvR4kbtef5pyJReN5azN7ECs00EZHj03zLkNh/gPAl2WNAYr1o1VCZg/h6B
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: passwd
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  jooq:
    sql-dialect: MySQL
  profiles:
    include: SECRET

logging:
  level:
    org:
      jooq:
        tools:
          LoggerListener: DEBUG
jasypt:
  encryptor:
    bean: jasyptStringEncryptor