#해당 파일을 application-SECRET.yaml 으로 변경, "${--}"들을 실제 프로젝트 비밀번호로 변경
#jasypt:
#  encryptor:
#    password: ${--}

#spring:
#  security:
#    oauth2:
#      client:
#        registration:
#          google:
#            client-id: ${--}
#            client-secret: ${--}
#            scope:
#              - ${--}